version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0-ce-git
    environment:
      project: "circleci-integration-test"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install docker-compose
          command: |
            apk --update add py2-pip
            pip install docker-compose
            docker-compose --version
      - run:
          name: Start Container
          command: |
            docker-compose -p "$project" up -d
            sleep 5
            docker-compose -p "$project" ps
      - run:
          name: Let client talk to server
          command: |
            docker-compose -p "$project" run client psql -h server -p 5432 -U postgres -c "\l"
