version: 2
jobs:

  build:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install docker-compose
          command: apk --update add py2-pip
                   /usr/bin/pip2 install docker-compose
                   docker-compose --version
      - run:
          name: Start Container
          command: docker-compose up -d
                   docker-compose ps
      - run:
          name: Let client talk to server
          command: docker-compose run client
                     psql -h server -p 5432 -U postgres -c "\l"
